### ISSUE TITLE
Can't do sudo in exagear environment 

### ISSUE THREAD

**Issue by Octonath** [ryanfortner/exagear-rpi#3]
Hey so installing did very well but after that I can't seem to do sudo command, it says that I have a syntax error near line 27 but I have never modified the file. So if you encountered this problem before I could use a fix.

Thanks in advance

**Comment by ryanfortner** [comment]
Another user encountered this error in https://github.com/ryanfortner/exagear-rpi/issues/4. Please see my comment there.
