### ISSUE TITLE
Syntax Error w/ sudo - Issue 

### ISSUE THREAD

**Issue by pr0cqd** [ryanfortner/exagear-rpi#4]
Hey OP. Exagear runs into an Issue everytime trying to use the sudo commad. 
Any known Fixes you have for this specific Problem? Exagear is the only Program that would let me use x86 on aarm. 
I know this is such a Niche Software for Linux but i'd hugely appreciate it if you could help a fella out. 

Well and here is the Error Code. 

>>> /etc/sudoers: syntax error near line 27 <<<
sudo: parse error in /etc/sudoers near line 27
sudo: no valid sudoers sources found, quitting
sudo: unable to initialize policy plugin

**Comment by ryanfortner** [comment]
Does sudo work on the host system? (without exagear)

**Comment by pr0cqd** [comment]
> Does sudo work on the host system? (without exagear) 

Yep, doesnt pop any errors

**Comment by frankhval** [comment]
can confirm; I've tried several guest images and if I try to use sudo <anything> I got the same mistake whatever I do with the sudoers file :(

Main system works just fine otoh

**Comment by frankhval** [comment]
Update for anyone who will bump into the same problem from the future: By some strange magic ExaGear session was looking into the main system's sudoers and on recent raspberry pi's OS images the line 27 of sudoers is looking like "@includedir ...".

By changing line 27 from "@includedir..." to "#includedir..." on a host system '/etc/sudoers' solves the problem.

Hope it will be helpful for anyone except myself.

**Comment by pr0cqd** [comment]
> Update for anyone who will bump into the same problem from the future: By some strange magic ExaGear session was looking into the main system's sudoers and on recent raspberry pi's OS images the line 27 of sudoers is looking like "@includedir ...".
> 
> By changing line 27 from "@includedir..." to "#includedir..." on a host system '/etc/sudoers' solves the problem.
> 
> Hope it will be helpful for anyone except myself.

Wow, This is actually quite the surprise. 
Thank you. Never thought I'd see that Issue fixed.

**Comment by pranavr2003** [comment]
> Update for anyone who will bump into the same problem from the future: By some strange magic ExaGear session was looking into the main system's sudoers and on recent raspberry pi's OS images the line 27 of sudoers is looking like "@includedir ...".
> 
> By changing line 27 from "@includedir..." to "#includedir..." on a host system '/etc/sudoers' solves the problem.
> 
> Hope it will be helpful for anyone except myself.

**Are you God?**
